---
- name: Install Apache Tomcat using ansible
  hosts: all
  user: root
  tasks:
    - name: Update the System Packages
      yum:
        name: '*'
        state: latest
        update_cache: yes
 
    - name: Create a Tomcat User
      user:
        name: tomcat
 
    - name: Create a Tomcat Group
      group:
        name: tomcat
 
    - name: Install JAVA
      yum:
        name: java-1.8.0
        state: present
 
 
    - name: Create a Tomcat Directory
      file:
        path: /opt/tomcat
        owner: tomcat
        group: tomcat
        mode: 755
        recurse: yes
 
    - name: download & unarchive tomcat10 
      unarchive:
        src: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.5/bin/apache-tomcat-10.1.5.tar.gz
        dest: /opt/tomcat
        remote_src: yes
        extra_opts: [--strip-components=1]
 
    - name: Change ownership of tomcat directory
      file:
        path: /opt/tomcat
        owner: tomcat
        group: tomcat
        mode: "u+rwx,g+rx,o=rx"
        recurse: yes
        state: directory
 
    - name: Creating a service file
      copy: 
       content: |-
        [Unit]
        Description=Apache Tomcat
        After=syslog.target network.target

        [Service]
        Type=forking

        Environment=JAVA_HOME=/usr/lib/jvm/jre-1.8.0-openjdk
        Environment=CATALINA_PID=/opt/tomcat/temp/tomcat.pid
        Environment=CATALINA_HOME=/opt/tomcat
        Environment=CATALINA_BASE=/opt/tomcat
        Environment='CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC'
        Environment='JAVA_OPTS=-Djava.awt.headless=true -Djava.security.egd=file:/dev/./urandom'
        PIDFile=/opt/tomcat/temp/tomcat.pid
        ExecStart=/opt/tomcat/bin/startup.sh
        ExecStop=/opt/tomcat/bin/shutdown.sh

        [Install]
        WantedBy=multi-user.target


       dest: /etc/systemd/system/tomcat.service
       mode: 755
    - name: Reload the SystemD to re-read configurations
      become: yes
      service:
        daemon-reload: yes
    - name: Enable the tomcat service and start
      become: yes
      service:
        name: tomcat
        enabled: yes
        state: started
